In [14]:
import numpy as np
mylist = [0,1,2,3,4,5,]
myarr = np.array(mylist)
type(myarr)
myarr

array([0, 1, 2, 3, 4, 5])

* ##Defining a matrix / 2d array

In [9]:
mymatrix = np.array([[0,1,5], [-2, 1,4], [7,8,9]])
mymatrix
mymatrix[0, :]

array([0, 1, 5])

In [11]:
mymatrix[:, len(mymatrix)-1]

array([5, 4, 9])

In [20]:
mymatrix[0:2, 2:4]

array([[5],
       [4]])

* #arange
* #Return evenly spaced values within a given interval

In [21]:
myarange = np.arange(10)
myarange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
myarangestep = np.arange(0,10,2)
myarange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

* zeroes and ones
* Generate arryas of zeroes and ones

In [25]:
z = np.zeros(4)

In [26]:
z1 = np.zeros((3,3))
z1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
z1 = np.ones((3,2))
z1

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Linspace

Return evenly spaced numbers over a specified interval

In [35]:
L = np.linspace(1,25,9)
L

array([ 1.,  4.,  7., 10., 13., 16., 19., 22., 25.])

In [39]:
L3 = L.reshape(3,3)
L3

array([[ 1.,  4.,  7.],
       [10., 13., 16.],
       [19., 22., 25.]])

eye
creates an identity matrix

In [45]:
I2 = np.eye(2, 3)
I2

array([[1., 0., 0.],
       [0., 1., 0.]])

In [51]:
I2[0:2, 0:2]

array([[1., 0.],
       [0., 1.]])

random

In [52]:
import random

rand - creates an array of the given shape and populate it with random samples from a uniform distribution over [0,1]

In [55]:
arr = np.random.rand(3,4)
arr

array([[0.31319798, 0.90806878, 0.35509975, 0.21081341],
       [0.43288941, 0.35896337, 0.27885148, 0.28819784],
       [0.31260426, 0.73201389, 0.29225883, 0.99435179]])

In [58]:
array1 = np.random.randint(0, 5)
array1

0

In [59]:
from numpy.random import rand
arr_simple = rand(3, 4)
arr_simple

In [67]:
from numpy.random import randint
arr_simple = randint(3, 10)
arr_simple

3

randn - returns sample/samples from the "standard normal" distribution. Unlike rand which is uniform

In [69]:
mat = np.random.randn(3,2)
mat

array([[-0.26138828,  0.5121374 ],
       [-0.12496954,  0.83758597],
       [ 0.4051529 ,  1.02460496]])

max, min, argmax, argmin
These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [76]:
seq = [i for i in range(5)]
seq

[0, 1, 2, 3, 4]

In [77]:
l = lambda x: x**2
l(5)

25

In [81]:
l = lambda x:x.split("@")[0]
l("aayushkab.2003@gmail.com")

'aayushkab.2003'